### ISSUE TITLE
weights file

### ISSUE THREAD

**Issue by smolboii** [zamponotiropita/Mask_RCNN#3]
hi,

would it be possible to have a .h5 file uploaded with the weights obtained after training on the NYU dataset? im trying to train an RGB-D model on a small custom dataset and would rather not train a pretrained model on the NYU dataset from scratch, if possible

thanks :)

**Comment by Bill4869** [comment]
@smolboii Hi,
I was wondering whether you did train a pretrained model on the NYU dataset from scratch?

**Comment by orestis-z** [comment]
Hello. I trained from scratch + unfortunately, I don't have the weights at hand anymore
