### ISSUE TITLE
NYU Depth v2 dataset problems

### ISSUE THREAD

**Issue by Albert-learner** [zamponotiropita/Mask_RCNN#4]
https://github.com/orestis-z/mask-rcnn-rgbd/blob/d590e0f5085f8cbe895a6698e284426fd0116aa4/instance_segmentation/NYU-Depth_V2/dataset.py#L19

Hello, I'd like to use your code for instance segmentation at NYU Depth v2 dataset. But when I execute generate_np_data.py, the folder named 'data' made and there's no 'names' property at data folder. So I couldn't import this line, "from data.names import names". Could you tell me how to do this? Thank you. 

My Error Message is this,
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_3488/2422544616.py in <module>
      1 from instance_segmentation.objects_config import ObjectsConfig
      2 from instance_segmentation.objects_dataset import ObjectsDataset, normalize
----> 3 from data.names import names

ModuleNotFoundError: No module named 'data.names'

**Comment by orestis-z** [comment]
You need to run https://github.com/orestis-z/mask-rcnn-rgbd/blob/master/instance_segmentation/NYU-Depth_V2/generate_np_data.py first to generate the names from the matlab file
